todoapp:

  namespace: todoapp

  image:
    name: ikulyk404/todoapp
    version: 4.0.1

  secrets:
      SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
      DB_NAME: "app_db"
      DB_USER: "app_user"
      DB_PASSWORD: "1234"
      DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"

  resources:
      requests:
        memory: "256Mi"
        cpu: "150m"
      limits:
        memory: "256Mi"
        cpu: "150m"

  rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  nodeAffinity:
    type: preferredDuringSchedulingIgnoredDuringExecution
    weight: 1
    key: app
    operator: In

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpuAvgUtilization: 70
    memoryAvgUtilization: 70

  pv:
    capacity: 1Gi

  pvc:
    requestsStorageCapacity: 1Gi

  security:
    serviceAccountName: secrets-reader
